// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3J6FYqysR3sMra42bJEgVpJe99hnKYnc',
    appId: '1:811901014247:web:74fad2cb6caed1cc5c9242',
    messagingSenderId: '811901014247',
    projectId: 'vibecheck-app-b5cb0',
    authDomain: 'vibecheck-app-b5cb0.firebaseapp.com',
    storageBucket: 'vibecheck-app-b5cb0.firebasestorage.app',
    measurementId: 'G-ZX7BYN2J4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwmedvgR7ZnaIBQhHyKsPvqxZzpwkrLLw',
    appId: '1:811901014247:android:3b8936358ada7fc45c9242',
    messagingSenderId: '811901014247',
    projectId: 'vibecheck-app-b5cb0',
    storageBucket: 'vibecheck-app-b5cb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcuBmMH9ilIDW5WjQWaZ8Ce12t-yOgCgw',
    appId: '1:811901014247:ios:efedeaf3ef9339555c9242',
    messagingSenderId: '811901014247',
    projectId: 'vibecheck-app-b5cb0',
    storageBucket: 'vibecheck-app-b5cb0.firebasestorage.app',
    iosBundleId: 'com.example.vibecheckApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcuBmMH9ilIDW5WjQWaZ8Ce12t-yOgCgw',
    appId: '1:811901014247:ios:efedeaf3ef9339555c9242',
    messagingSenderId: '811901014247',
    projectId: 'vibecheck-app-b5cb0',
    storageBucket: 'vibecheck-app-b5cb0.firebasestorage.app',
    iosBundleId: 'com.example.vibecheckApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3J6FYqysR3sMra42bJEgVpJe99hnKYnc',
    appId: '1:811901014247:web:9a5ba43e5911c61e5c9242',
    messagingSenderId: '811901014247',
    projectId: 'vibecheck-app-b5cb0',
    authDomain: 'vibecheck-app-b5cb0.firebaseapp.com',
    storageBucket: 'vibecheck-app-b5cb0.firebasestorage.app',
    measurementId: 'G-TZ1JS8CQSK',
  );
}
